#!/usr/bin/env python3
"""Aggregate MoE optimization-level study (configs/moe_variants/C*.yaml).

For each cell (C0..C6) reads hardware_view.json + bench.jsonl and emits:
  results/regime_bench/moe_opt_levels_table.{csv,md}
"""
from __future__ import annotations
import csv, json, glob, os, sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[2]


def parse_bench(bench_path):
    """bench.jsonl is appended by sglang.bench_serving; we want the LAST row."""
    if not os.path.exists(bench_path): return {}
    rows = [json.loads(l) for l in open(bench_path) if l.strip()]
    return rows[-1] if rows else {}


def main():
    hv_root = PROJECT_ROOT / "experiments/tmp/moe_opt_levels"
    out_dir = PROJECT_ROOT / "results/regime_bench"
    out_dir.mkdir(parents=True, exist_ok=True)

    rows = []
    for d in sorted(hv_root.iterdir()):
        if not d.is_dir(): continue
        tag = d.name
        hv = d / "hardware_view.json"
        if not hv.exists():
            rows.append({"tag": tag, "status": "MISSING"})
            continue
        data = json.loads(hv.read_text())
        rc = data.get("rc")
        bench = parse_bench(str(d / "bench.jsonl"))
        gpu = data.get("gpu_sampling") or {}
        si = data.get("server_info_excerpt") or {}
        prof_t = data.get("profile_totals") or {}
        top = data.get("top_kernels") or []
        kcat = data.get("kernel_category_pct") or {}

        row = {
            "tag": tag,
            "status": "PASS" if rc == 0 and top else "FAIL",
            "rc": rc,
            "wall_window_s": data.get("wall_window_s"),
            # backend
            "attention_backend": si.get("attention_backend"),
            "sampling_backend": si.get("sampling_backend"),
            "schedule_policy": si.get("schedule_policy"),
            # perf from bench
            "request_throughput": bench.get("request_throughput"),
            "output_throughput": bench.get("output_throughput"),
            "ttft_mean_ms": bench.get("mean_ttft_ms"),
            "ttft_p95_ms": bench.get("p99_ttft_ms"),  # bench_serving doesn't emit p95; using p99 as proxy
            "ttft_p99_ms": bench.get("p99_ttft_ms"),
            "tpot_mean_ms": bench.get("mean_tpot_ms"),
            "itl_p95_ms": bench.get("p95_itl_ms"),
            "e2e_p99_ms": bench.get("p99_e2e_latency_ms"),
            "completed": bench.get("completed"),
            # hardware
            "gpu_mem_peak_GiB": round(gpu.get("memory_used_mib_peak", 0)/1024, 2) if gpu.get("memory_used_mib_peak") else None,
            "gpu_util_mean_pct": gpu.get("utilization_gpu_pct_mean"),
            "mem_ctrl_util_pct": gpu.get("utilization_mem_pct_mean"),
            "power_mean_W": gpu.get("power_w_mean"),
            "power_peak_W": gpu.get("power_w_peak"),
            "sm_clock_mhz_mean": gpu.get("sm_clock_mhz_mean"),
            # kernel mix
            "trace_wall_ms": prof_t.get("wallclock_ms"),
            "trace_gpu_active_ms": prof_t.get("gpu_active_ms"),
            "kernel_cats_top": ", ".join(f"{k}:{v}%" for k, v in list(kcat.items())[:5]),
            "top_kernel_1_name": top[0].get("name_short", "")[:55] if top else None,
            "top_kernel_1_pct": top[0].get("self_time_pct") if top else None,
            "top_kernel_1_calls": top[0].get("calls") if top else None,
            "top_kernel_2_name": top[1].get("name_short", "")[:55] if len(top) > 1 else None,
            "top_kernel_2_pct": top[1].get("self_time_pct") if len(top) > 1 else None,
        }
        rows.append(row)

    # CSV
    csv_path = out_dir / "moe_opt_levels_table.csv"
    keys = list(rows[0].keys()) if rows else []
    # union of keys (handle MISSING)
    seen = set()
    for r in rows:
        for k in r.keys():
            if k not in seen: keys.append(k); seen.add(k)
    keys = list(dict.fromkeys(keys))
    with open(csv_path, 'w', newline='') as f:
        w = csv.DictWriter(f, fieldnames=keys)
        w.writeheader()
        for r in rows:
            w.writerow({k: ("" if r.get(k) is None else r.get(k)) for k in keys})

    # Markdown
    md = out_dir / "moe_opt_levels_table.md"
    lines = ["# MoE optimization-knob study — Qwen3-30B-A3B on R8 (prefix sharing)",
             "",
             "Single regime (R8, MoE's throughput champion). 7 config variants under test.",
             "All tables here generated by `scripts/regime_study/aggregate_moe_opt_levels.py`.",
             ""]

    # Table 1 — Status
    lines.append("## 1. Status overview")
    lines.append("")
    lines.append("| Tag | Status | rc | Backend (att/sched) | Wall (s) | Reason if FAIL |")
    lines.append("|---|---|---|---|---|---|")
    fail_notes = {
        "C1_torch_compile": "torch.compile dynamo AssertionError on `rotary_embedding.py:272`",
        "C5_attn_flashinfer": "flashinfer ninja JIT build of prefill kernel failed (env issue)",
    }
    for r in rows:
        att = r.get("attention_backend") or "—"
        sch = r.get("schedule_policy") or "—"
        wall = r.get("wall_window_s")
        wall_s = f"{wall:.1f}" if wall else "—"
        note = fail_notes.get(r["tag"], "" if r["status"] == "PASS" else "see server.log")
        lines.append(f"| **{r['tag']}** | {r['status']} | {r.get('rc')} | {att} / {sch} | {wall_s} | {note} |")
    lines.append("")

    # Table 2 — Performance
    lines.append("## 2. Performance (sglang.bench_serving)")
    lines.append("")
    lines.append("| Tag | Req/s | Out tok/s | TTFT mean ms | TTFT p99 ms | TPOT mean ms | ITL p95 ms | E2E p99 ms | Completed |")
    lines.append("|---|---|---|---|---|---|---|---|---|")
    for r in rows:
        if r["status"] != "PASS":
            lines.append(f"| {r['tag']} | FAIL | | | | | | | |")
            continue
        def fm(v, p=1):
            if v is None: return "—"
            if isinstance(v, float): return f"{v:.{p}f}"
            return str(v)
        lines.append(f"| **{r['tag']}** | {fm(r['request_throughput'],2)} | {fm(r['output_throughput'],0)} | "
                     f"{fm(r['ttft_mean_ms'],1)} | {fm(r['ttft_p99_ms'],1)} | "
                     f"{fm(r['tpot_mean_ms'],2)} | {fm(r['itl_p95_ms'],2)} | "
                     f"{fm(r['e2e_p99_ms'],0)} | {fm(r['completed'])} |")
    lines.append("")

    # Table 3 — Hardware
    lines.append("## 3. Hardware (nvidia-smi during bench window)")
    lines.append("")
    lines.append("| Tag | Mem peak (GiB) | GPU util mean % | Mem-ctrl util % | Power mean (W) | Power peak (W) | SM clock mean (MHz) |")
    lines.append("|---|---|---|---|---|---|---|")
    for r in rows:
        if r["status"] != "PASS":
            lines.append(f"| {r['tag']} | — | — | — | — | — | — |")
            continue
        def fm(v, p=1):
            if v is None: return "—"
            if isinstance(v, float): return f"{v:.{p}f}"
            return str(v)
        lines.append(f"| **{r['tag']}** | {fm(r['gpu_mem_peak_GiB'],2)} | {fm(r['gpu_util_mean_pct'],1)} | "
                     f"{fm(r['mem_ctrl_util_pct'],1)} | {fm(r['power_mean_W'],0)} | {fm(r['power_peak_W'],0)} | "
                     f"{fm(r['sm_clock_mhz_mean'],0)} |")
    lines.append("")

    # Table 4 — Kernel mix
    lines.append("## 4. Kernel mix (top-20 GPU events; from torch.profiler)")
    lines.append("")
    lines.append("| Tag | Trace wall (ms) | GPU active (ms) | Kernel categories (top 5) |")
    lines.append("|---|---|---|---|")
    for r in rows:
        if r["status"] != "PASS":
            lines.append(f"| {r['tag']} | — | — | — |")
            continue
        def fm(v, p=1):
            if v is None: return "—"
            if isinstance(v, float): return f"{v:.{p}f}"
            return str(v)
        lines.append(f"| **{r['tag']}** | {fm(r['trace_wall_ms'],1)} | {fm(r['trace_gpu_active_ms'],1)} | "
                     f"{r['kernel_cats_top']} |")
    lines.append("")

    # Table 5 — Top-2 kernel names
    lines.append("## 5. Top-2 kernels per cell (the actual kernel name on GPU)")
    lines.append("")
    lines.append("| Tag | #1 kernel | #1 % | calls | #2 kernel | #2 % |")
    lines.append("|---|---|---|---|---|---|")
    for r in rows:
        if r["status"] != "PASS":
            lines.append(f"| {r['tag']} | — | — | — | — | — |")
            continue
        n1 = r.get("top_kernel_1_name") or ""
        n2 = r.get("top_kernel_2_name") or ""
        lines.append(f"| **{r['tag']}** | `{n1}` | {r.get('top_kernel_1_pct')}% | "
                     f"{r.get('top_kernel_1_calls')} | `{n2}` | {r.get('top_kernel_2_pct')}% |")
    lines.append("")

    md.write_text("\n".join(lines))
    print(f"wrote {csv_path}")
    print(f"wrote {md}")


if __name__ == "__main__":
    main()
