#!/usr/bin/env python3
"""Stage 1: assemble v1 problem packages from suspicious cases.

This is the v0.4 replacement for `select_cases_for_stage2.py`. It produces
**self-contained problem packages** under `experiments/problems/PNNN/`
matching the schema in `docs/problem-package/schema.md`.

Each problem package contains:
  - problem.json              (umbrella contract)
  - workload.yaml             (target, frozen copy)
  - baseline_metrics.json     (L1: target metrics)
  - server_features.json      (L2: target log mining)
  - classification.json       (L3: target classification)
  - profile_summary.json      (L4: null for v0.4 — agent-decided)
  - neighbors/                (boundary-expansion neighbors + their metrics + features)
  - controls/                 (unrelated workloads as negative control)
  - hypothesis.md             (auto-drafted from evidence; setter polishes)
  - acceptance_criteria.json  (auto-drafted from scoring)
  - attempts/                 (empty; solver writes here)

Rules:
  1. Score ≥ threshold OR hard failure → selected.
  2. At most 1 problem per regime_hint cluster (diversity).
  3. At most --max-problems total.
  4. Every problem MUST have ≥1 neighbor (from the boundary-expansion data already
     in raw_results.jsonl). Without a neighbor, skip and emit a warning.
  5. Every problem MUST have ≥1 control (preferred: a clean-pass workload with a
     different regime_hint).

After this script runs, anyone can:
  - tar/zip the problem dir and share it
  - run a solver against it
  - re-validate the cliff by re-running the target workload
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

from utils import (
    append_jsonl,
    load_json,
    load_yaml,
    now_str,
    read_jsonl,
    save_json,
    save_yaml,
)


# ---------- selection ----------

def pick_problems(
    scored: list[dict],
    raw_by_run: dict[str, dict],
    threshold: float,
    max_problems: int,
) -> list[dict]:
    """Choose which scored cases become problems."""
    chosen: list[dict] = []
    seen_clusters: set[str] = set()

    # Hard failures always selected first
    for s in scored:
        if s.get("status") == "fail" and (s.get("failure_kind") or "") in {
            "oom",
            "server_crash",
            "timeout",
        }:
            chosen.append(s)
            seen_clusters.add(s.get("regime_hint"))
            if len(chosen) >= max_problems:
                return chosen

    # Then top-scored passed runs, one per cluster
    for s in scored:
        if s.get("status") != "pass":
            continue
        if (s.get("score") or 0.0) < threshold:
            continue
        hint = s.get("regime_hint")
        if hint in seen_clusters:
            continue
        chosen.append(s)
        seen_clusters.add(hint)
        if len(chosen) >= max_problems:
            break
    return chosen


# ---------- neighbor + control discovery ----------

def find_neighbors(
    target_scored: dict, raw_by_run: dict[str, dict]
) -> list[dict]:
    """A neighbor is a passed run with the same regime_hint as the target,
    different workload, generated by boundary-expansion.

    We detect boundary-expansion outputs by the workload yaml having a
    `source.generated_by == "boundary-expansion"` field, AND the parent
    pointing at the target's workload file.
    """
    target_workload = target_scored["workload_file"]
    target_hint = target_scored.get("regime_hint")
    neighbors: list[dict] = []
    for run_id, rec in raw_by_run.items():
        if rec.get("status") != "pass":
            continue
        if rec.get("regime_hint") != target_hint:
            continue
        if rec["workload_file"] == target_workload:
            continue
        wl = Path(rec["workload_file"])
        if not wl.exists():
            continue
        wl_doc = load_yaml(wl)
        src = wl_doc.get("source") or {}
        if src.get("generated_by") != "boundary-expansion":
            continue
        if Path(src.get("parent", "")).resolve() != Path(target_workload).resolve():
            continue
        neighbors.append(rec)
    # sort by axis value for deterministic ordering
    neighbors.sort(key=lambda r: (
        (load_yaml(Path(r["workload_file"])).get("source") or {}).get("axis_value", 0)
    ))
    return neighbors


def find_controls(
    target_scored: dict, raw_by_run: dict[str, dict], n: int = 1
) -> list[dict]:
    """A control is any passed clean run with a DIFFERENT regime_hint and a
    fundamentally different dataset shape — so a fix on the target should not
    affect controls (much).

    Strategy: prefer `smoke` (the canonical noise-floor workload); fall back
    to other passed clean-pass workloads in different hints.
    """
    target_hint = target_scored.get("regime_hint")
    controls: list[dict] = []

    # Prefer smoke
    for rec in raw_by_run.values():
        if rec.get("status") != "pass":
            continue
        if rec.get("regime_hint") == target_hint:
            continue
        if (rec.get("workload_name") or "").startswith("smoke"):
            controls.append(rec)
            break

    # Fill with other distinct-hint clean passes
    seen_hints = {target_hint} | {r.get("regime_hint") for r in controls}
    for rec in raw_by_run.values():
        if len(controls) >= n:
            break
        if rec.get("status") != "pass":
            continue
        if rec.get("regime_hint") in seen_hints:
            continue
        controls.append(rec)
        seen_hints.add(rec.get("regime_hint"))

    return controls[:max(n, 1)]


# ---------- per-package assembly ----------

def copy_file(src: Path, dst: Path) -> None:
    dst.parent.mkdir(parents=True, exist_ok=True)
    if src.exists():
        dst.write_bytes(src.read_bytes())


def assemble_workload_block(
    rec: dict, dest_dir: Path, prefix: str
) -> dict:
    """Copy workload yaml + metrics + (best-effort) server features into dest_dir.
    Returns a dict describing where things landed (relative paths from
    dest_dir's parent = the problem dir)."""
    name = rec["workload_name"]
    run_dir = Path(rec["run_dir"]) if rec.get("run_dir") else None
    src_wl = Path(rec["workload_file"])

    # workload yaml
    wl_dest = dest_dir / f"{name}.yaml"
    copy_file(src_wl, wl_dest)

    # metrics (canonical name `*_metrics.json` in run_dir)
    metrics_dest = dest_dir / f"{name}_baseline_metrics.json"
    if run_dir and run_dir.exists():
        cand = list(run_dir.glob("*_metrics.json"))
        if cand:
            copy_file(cand[0], metrics_dest)

    # server features (optional)
    features_dest = dest_dir / f"{name}_server_features.json"
    if run_dir and (run_dir / "server_features.json").exists():
        copy_file(run_dir / "server_features.json", features_dest)

    classification_dest = dest_dir / f"{name}_classification.json"
    if run_dir and (run_dir / "classification.json").exists():
        copy_file(run_dir / "classification.json", classification_dest)

    return {
        "name": name,
        "workload": f"{prefix}/{wl_dest.name}",
        "baseline_metrics": (
            f"{prefix}/{metrics_dest.name}" if metrics_dest.exists() else None
        ),
        "server_features": (
            f"{prefix}/{features_dest.name}" if features_dest.exists() else None
        ),
        "classification": (
            f"{prefix}/{classification_dest.name}" if classification_dest.exists() else None
        ),
    }


def assemble_target_block(rec: dict, problem_dir: Path) -> dict:
    """Target lives directly in the problem dir, not in a subdir."""
    name = rec["workload_name"]
    run_dir = Path(rec["run_dir"]) if rec.get("run_dir") else None
    src_wl = Path(rec["workload_file"])

    # workload.yaml (named generically for the target)
    copy_file(src_wl, problem_dir / "workload.yaml")

    # baseline_metrics.json
    if run_dir:
        cand = list(run_dir.glob("*_metrics.json"))
        if cand:
            copy_file(cand[0], problem_dir / "baseline_metrics.json")
        if (run_dir / "server_features.json").exists():
            copy_file(run_dir / "server_features.json",
                      problem_dir / "server_features.json")
        if (run_dir / "classification.json").exists():
            copy_file(run_dir / "classification.json",
                      problem_dir / "classification.json")

    return {
        "workload": "workload.yaml",
        "baseline_metrics": "baseline_metrics.json",
        "server_features": "server_features.json",
        "classification": "classification.json",
        "profile_summary": None,
        "skip_L4_reason": "v0.4: setter agent did not opt in to deep profile",
        "repeats": [],
    }


# ---------- evidence + suggested strategies + hypothesis ----------

REGIME_KNOB_PRIORS = {
    "scheduler_tail": [
        {"knob": "max-running-requests", "direction": "increase",
         "values_to_try": [64, 96, 128],
         "expected_improvement_pct": 60,
         "rationale": "If concurrency_capped, raising admission cap should drain the queue."},
        {"knob": "cuda-graph-max-bs", "direction": "increase",
         "values_to_try": [64, 128],
         "expected_improvement_pct": 20,
         "rationale": "Allows CUDA-graph fast path at higher running req counts."},
    ],
    "prefill_boundary": [
        {"knob": "chunked-prefill-size", "direction": "set",
         "values_to_try": [2048, 4096, 8192],
         "expected_improvement_pct": 25,
         "rationale": "Chunked prefill smooths long-input cost across iterations."},
        {"knob": "max-prefill-tokens", "direction": "increase",
         "values_to_try": [32768, 65536],
         "expected_improvement_pct": 15,
         "rationale": "Larger prefill budget may amortize long-input cost."},
    ],
    "prefill": [
        {"knob": "chunked-prefill-size", "direction": "set",
         "values_to_try": [4096, 8192],
         "expected_improvement_pct": 15,
         "rationale": "Smooth prefill cost."},
    ],
    "decode_saturation": [
        {"knob": "num-continuous-decode-steps", "direction": "increase",
         "values_to_try": [2, 4],
         "expected_improvement_pct": 15,
         "rationale": "Amortize scheduler overhead across multiple decode steps."},
    ],
    "decode": [
        {"knob": "num-continuous-decode-steps", "direction": "increase",
         "values_to_try": [2, 4],
         "expected_improvement_pct": 10,
         "rationale": "Reduce scheduler overhead per decoded token."},
    ],
    "prefix_cache": [
        {"knob": "schedule-policy", "direction": "set",
         "values_to_try": ["lpm", "fcfs"],
         "expected_improvement_pct": 15,
         "rationale": "LPM gives prefix-aware scheduling."},
    ],
    "cache_churn": [
        {"knob": "disable-radix-cache", "direction": "set",
         "values_to_try": [True, False],
         "expected_improvement_pct": 10,
         "rationale": "Ablate radix cache to confirm churn cost."},
    ],
}


def build_suggested_strategies(target_scored: dict) -> list[dict]:
    hint = (target_scored.get("regime_hint") or "").lower()
    priors = REGIME_KNOB_PRIORS.get(hint) or REGIME_KNOB_PRIORS.get("scheduler_tail")
    out = []
    for i, p in enumerate(priors, start=1):
        out.append({
            "strategy_id": f"S{i:03d}",
            "kind": "config",
            "route_to": "config-agent",
            "knob": p["knob"],
            "direction": p.get("direction"),
            "values_to_try": p["values_to_try"],
            "expected_improvement_pct": p["expected_improvement_pct"],
            "rationale": p["rationale"],
            "risk": "low for v0.4; verify via controls"
        })
    return out


def build_evidence(target_scored: dict) -> dict:
    """Translate scored row → problem.evidence block."""
    components = target_scored.get("components") or {}
    signals: list[dict] = []

    def push(source: str, field: str, value: Any, weight: str) -> None:
        if value is None:
            return
        signals.append({
            "source": source, "field": field, "value": value, "weight": weight
        })

    sls = components.get("server_log_signal", {}).get("evidence", {})
    push("server_features.json", "concurrency_capped",
         sls.get("contributions", {}).get("concurrency_capped") is not None,
         "high")
    push("server_features.json", "peak_queue_reqs", sls.get("peak_queue_reqs"), "high")
    push("server_features.json", "max_running_requests", sls.get("max_running_requests"), "high")
    push("server_features.json", "peak_token_usage", sls.get("peak_token_usage"), "medium")

    cls = components.get("failure_class", {}).get("evidence", {})
    push("classification.json", "classification", cls.get("classification"), "high")

    tlr = components.get("tail_latency_ratio", {}).get("evidence", {})
    push("baseline_metrics.json", "tail_p99_over_p50", tlr.get("max_ratio"), "medium")

    ln = components.get("local_nonlinearity_primary", {}).get("evidence", {})
    push("baseline_metrics.json", "ratio_worse_than_nearest_neighbor",
         ln.get("ratio_worse_than_nb"), "high")

    layers = ["L1", "L2", "L3"]
    if any(s["source"] == "profile_summary.json" for s in signals):
        layers.append("L4")

    return {
        "layers_collected": layers,
        "key_signals": signals,
        "bias_check": {
            "repeats_n": 1,
            "primary_metric_cv_pct": None,
            "metric_stable": None,
            "note": "v0.4: single-repeat; setter agent did not opt in to L5 bias removal",
        },
        "ruled_out": [],
    }


def build_hypothesis_md(target_scored: dict, target_workload: dict, neighbors: list[dict]) -> str:
    name = target_scored["workload_name"]
    score = target_scored.get("score")
    classification = target_scored.get("classification")
    primary_metric = target_scored.get("primary_metric")
    primary_value = target_scored.get("primary_value")

    lines = []
    lines.append(f"# Hypothesis for {name}\n")
    lines.append("## Symptom\n")
    lines.append(
        f"The target workload `{name}` produced "
        f"`{primary_metric} = {primary_value:.2f}` (lower-is-better). "
        f"Classification: **{classification}**. Suspicion score: **{score:.3f}**.\n"
    )

    if neighbors:
        lines.append("## Why we believe this is a cliff, not noise\n")
        for n in neighbors:
            m = n.get("metrics") or {}
            v = m.get(primary_metric)
            wl = load_yaml(Path(n["workload_file"]))
            axis_val = (wl.get("source") or {}).get("axis_value")
            axis = (wl.get("source") or {}).get("axis")
            if v is not None:
                lines.append(
                    f"- Neighbor `{n['workload_name']}` ({axis}={axis_val}) "
                    f"has `{primary_metric} = {v:.2f}` — bracket evidence.\n"
                )

    components = target_scored.get("components") or {}
    sls = components.get("server_log_signal", {}).get("evidence", {})
    if sls.get("contributions"):
        lines.append("\n## Server-log evidence\n")
        for k, _ in sls["contributions"].items():
            lines.append(f"- `{k}` is True\n")
        for fld in ("peak_running_reqs", "peak_queue_reqs",
                    "max_running_requests", "peak_token_usage"):
            v = sls.get(fld)
            if v is not None:
                lines.append(f"- `{fld}` = {v}\n")

    lines.append("\n## Suggested mechanism\n")
    hint = (target_scored.get("regime_hint") or "").lower()
    if "scheduler" in hint and sls.get("contributions", {}).get("concurrency_capped"):
        lines.append(
            "The server's admission cap (`max_running_requests`) is below the "
            "workload's `max_concurrency`; requests queue and observe long TTFT. "
            "Raising the cap should reduce queueing without hurting steady-state.\n"
        )
    elif "prefill" in hint:
        lines.append(
            "Long prefill cost is the dominant TTFT term; chunked prefill or a "
            "different prefill batch budget may help.\n"
        )
    elif "decode" in hint:
        lines.append(
            "Decode throughput is the primary constraint; reducing per-token "
            "scheduler overhead (e.g. `num-continuous-decode-steps`) should help.\n"
        )
    elif "prefix" in hint or "cache" in hint:
        lines.append(
            "Prefix-cache effectiveness depends on schedule policy and "
            "eviction settings; LPM scheduling and radix-cache ablation are the "
            "primary knobs.\n"
        )
    else:
        lines.append(
            "Mechanism is uncertain. Solver should run a deep profile (L4) "
            "before committing to a strategy.\n"
        )

    lines.append(
        "\n## Status\n\n"
        "This hypothesis was **auto-drafted** by `select_problems.py` from "
        "rule-based scoring evidence. A setter or solver agent should refine "
        "it once they have profile data.\n"
    )
    return "".join(lines)


def build_acceptance_criteria(target_scored: dict) -> dict:
    primary = target_scored.get("primary_metric") or "ttft_p95_ms"
    direction = target_scored.get("primary_direction") or "lower"
    return {
        "schema_version": 1,
        "primary": {
            "on": "target",
            "metric": primary,
            "direction": direction,
            "required_improvement_pct": 30.0,
            "stretch_improvement_pct": 60.0,
        },
        "constraints": [
            {"on": "target", "metric": "request_throughput",
             "direction": "higher", "max_regression_pct": 10.0},
            {"on": "controls.smoke", "metric": "ttft_p95_ms",
             "direction": "lower", "max_regression_pct": 5.0},
            {"on": "any", "metric": "oom", "max": 0},
            {"on": "any", "metric": "server_crash", "max": 0},
            {"on": "any", "metric": "failed_requests", "max": 0},
        ],
        "verification": {
            "always_paired_ab": False,
            "paired_ab_required_when_delta_lt_pct": 5.0,
            "min_repeats_per_workload_for_keep": 3,
        },
        "stretch_goals": [
            "Neighbor workloads also improve or remain unchanged.",
        ],
    }


# ---------- main ----------

def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--raw", default="regime_scout/outputs/raw_results.jsonl")
    ap.add_argument("--suspicious", default="regime_scout/outputs/suspicious_cases.jsonl")
    ap.add_argument("--server-config", default="configs/base.yaml")
    ap.add_argument("--problems-root", default="experiments/problems")
    ap.add_argument("--out", default="regime_scout/outputs/selected_problems.jsonl")
    ap.add_argument("--max-problems", type=int, default=5)
    ap.add_argument("--threshold", type=float, default=0.30)
    args = ap.parse_args()

    scored_rows = read_jsonl(args.suspicious)
    raw_rows = read_jsonl(args.raw)
    if not scored_rows:
        print(f"[select_problems] no scored rows in {args.suspicious}", file=sys.stderr)
        return 1

    raw_by_run: dict[str, dict] = {r["run_id"]: r for r in raw_rows}

    chosen = pick_problems(scored_rows, raw_by_run, args.threshold, args.max_problems)
    if not chosen:
        print(f"[select_problems] no cases met threshold {args.threshold}", file=sys.stderr)
        # still emit empty file so downstream knows we ran
        Path(args.out).write_text("")
        return 0

    server_cfg = load_yaml(args.server_config) if Path(args.server_config).exists() else {}
    problems_root = Path(args.problems_root)
    problems_root.mkdir(parents=True, exist_ok=True)

    out_jsonl = Path(args.out)
    if out_jsonl.exists():
        out_jsonl.unlink()

    for idx, target_scored in enumerate(chosen, start=1):
        problem_id = f"P{idx:03d}"
        problem_dir = problems_root / problem_id
        problem_dir.mkdir(parents=True, exist_ok=True)
        (problem_dir / "attempts").mkdir(exist_ok=True)

        target_run = raw_by_run.get(target_scored["run_id"])
        if not target_run:
            print(f"[select_problems] {problem_id}: no raw row for "
                  f"{target_scored['run_id']}; skipping", file=sys.stderr)
            continue

        # ---- target ----
        target_block = assemble_target_block(target_run, problem_dir)

        # ---- neighbors ----
        neighbors_dir = problem_dir / "neighbors"
        neighbors_dir.mkdir(exist_ok=True)
        neighbors_raw = find_neighbors(target_scored, raw_by_run)
        if not neighbors_raw:
            print(f"[select_problems] {problem_id}: no neighbors found; "
                  f"problem package is incomplete (skip later).", file=sys.stderr)
        neighbor_blocks = []
        for n in neighbors_raw:
            blk = assemble_workload_block(n, neighbors_dir, "neighbors")
            wl = load_yaml(Path(n["workload_file"]))
            axis = (wl.get("source") or {}).get("axis")
            axis_val = (wl.get("source") or {}).get("axis_value")
            blk["role"] = f"{axis}_neighbor" if axis else "neighbor"
            blk["axis"] = axis
            blk["axis_value"] = axis_val
            blk["expected_after_fix"] = "small_improvement_or_no_change"
            neighbor_blocks.append(blk)

        # ---- controls ----
        controls_dir = problem_dir / "controls"
        controls_dir.mkdir(exist_ok=True)
        controls_raw = find_controls(target_scored, raw_by_run, n=1)
        control_blocks = []
        for c in controls_raw:
            blk = assemble_workload_block(c, controls_dir, "controls")
            blk["role"] = "no_regression_check"
            control_blocks.append(blk)

        # ---- evidence ----
        evidence = build_evidence(target_scored)

        # ---- hypothesis ----
        hypothesis_md = build_hypothesis_md(
            target_scored, load_yaml(Path(target_run["workload_file"])), neighbors_raw
        )
        (problem_dir / "hypothesis.md").write_text(hypothesis_md)

        # ---- acceptance ----
        accept = build_acceptance_criteria(target_scored)
        save_json(accept, problem_dir / "acceptance_criteria.json")

        # ---- suggested strategies ----
        strategies = build_suggested_strategies(target_scored)

        # ---- final problem.json ----
        symptom = {
            "metric": target_scored.get("primary_metric"),
            "direction": "lower-is-better" if target_scored.get("primary_direction") == "lower"
                         else "higher-is-better",
            "observed_value": target_scored.get("primary_value"),
            "description": f"score {target_scored.get('score')} on "
                           f"{target_scored.get('primary_metric')} "
                           f"({target_scored.get('classification')})",
        }
        # nearest-neighbor ratio if we can compute it
        if neighbors_raw:
            nb_metric = (neighbors_raw[0].get("metrics") or {}).get(
                target_scored.get("primary_metric"))
            if nb_metric and target_scored.get("primary_value"):
                symptom["magnitude_vs_nearest_neighbor_pct"] = round(
                    100 * (target_scored["primary_value"] / nb_metric - 1.0), 1
                )

        problem = {
            "schema_version": 1,
            "problem_id": problem_id,
            "regime_id": f"R_{target_scored.get('regime_hint')}",
            "created_at": now_str(),
            "frozen": True,
            "model_path": server_cfg.get("model-path"),
            "hardware": "H200",
            "sglang_version": None,
            "sglang_commit": None,
            "baseline_config": str(Path(args.server_config).resolve()),
            "target": target_block,
            "symptom": symptom,
            "benchmark_suite": {
                "target": {
                    "workload": target_block["workload"],
                    "role": "must_improve",
                    "primary_metric": target_scored.get("primary_metric"),
                },
                "neighbors": neighbor_blocks,
                "controls": control_blocks,
            },
            "evidence": evidence,
            "hypothesis_md": "hypothesis.md",
            "suggested_strategies": strategies,
            "rejected_strategies": [],
            "acceptance_criteria_file": "acceptance_criteria.json",
            "lineage": {
                "stage1_run_dir": target_run.get("run_dir"),
                "neighbor_run_dirs": [n.get("run_dir") for n in neighbors_raw],
                "control_run_dirs": [c.get("run_dir") for c in controls_raw],
                "scoring_record": (
                    f"{args.suspicious}#run_id={target_scored['run_id']}"
                ),
                "noise_baseline": None,
            },
            "note_v04": (
                "Produced by select_problems.py from v0.3 rule-based scoring + "
                "wave-1 boundary expansion. L4 profile and L5 repeats were "
                "skipped (agent-decided). attempts/ is empty and awaits solver."
            ),
        }
        save_json(problem, problem_dir / "problem.json")

        # one-line index entry
        append_jsonl({
            "problem_id": problem_id,
            "regime_id": problem["regime_id"],
            "problem_dir": str(problem_dir),
            "problem_json": str(problem_dir / "problem.json"),
            "workload_yaml": str(problem_dir / "workload.yaml"),
            "primary_metric": target_scored.get("primary_metric"),
            "primary_value": target_scored.get("primary_value"),
            "suspicion_score": target_scored.get("score"),
            "n_neighbors": len(neighbor_blocks),
            "n_controls": len(control_blocks),
        }, out_jsonl)

        print(f"[select_problems] {problem_id}: {target_scored['workload_name']} "
              f"(score={target_scored.get('score')}, {len(neighbor_blocks)} neighbors, "
              f"{len(control_blocks)} controls) → {problem_dir}")

    print(f"[select_problems] {len(chosen)} problem(s) → {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
